{{- range .Values.init.application }}
{{- if .applicationEnabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-{{ .manifestId }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: initializer
spec:
  project: default

  source:
    repoURL: {{ .repository }}
    targetRevision: {{ .targetRevision }}
    path: {{ .path }}

    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
{{- end }}
{{- end }}