{{- range .Values.init.repository }}
---
apiVersion: v1
kind: Secret
metadata:
  name: initializer-{{ .manifestId }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{ .url }}
  password: {{ .password }}
  username: {{ .username }}
  insecure: "{{ .insecure }}"
  forceHttpBasicAuth: "{{ .forceHttpBasicAuth }}"
  enableLfs: "true"
{{- end }}