image:
  registry: docker.io
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent
auth:
  enabled: true
  database: python_backend
architecture: standalone
useStatefulSet: false
replicaCount: 1
persistence:
  enabled: true
  mountPath: /data/db
command: ["mongod", "--replSet", "debezium", "--bind_ip_all"]