apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: falco-exporter-service-scrape
  labels:
    app: falco-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: falco-exporter
  endpoints:
    - port: metrics
      path: /metrics