apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: falco-level-alert
spec:
  groups:
    - name: falco-level-alert
      rules:
        - alert: Falco Event Level Critical
          expr: rate(falco_events{priority="2"}[5m])
          labels:
            falco: "alert"
          annotations:
            description: Pod {{ printf "{{ $labels.k8s_ns_name }}" }} / {{ printf "{{ $labels.k8s_pod_name }}" }} is conflicting rule {{ printf "{{ $labels.source }}" }} / {{ printf "{{ $labels.rule }}"" }} with tags {{ printf "{{ $labels.tags }}" }}
            summary: Pod is violating a critical rule.
