kind: ConfigMap
apiVersion: v1
metadata:
  name: stunnel-{{ .Release.Name }}
data:
  STUNNEL_SERVICE: "smtps"
  STUNNEL_ACCEPT: "465"
  STUNNEL_CONNECT: {{ .Values.configuration.connect }}
  STUNNEL_KEY: "/tmp/certs/tls.key"
  STUNNEL_CRT: "/tmp/certs/tls.crt"
