apiVersion: v2
name: falco
version: 1.0.0
description: This Chart deploys falco.
dependencies:
  - name: falco
    version: 3.1.5
    repository: https://falcosecurity.github.io/charts
  - name: falcoexporter
    version: 0.9.6
    repository: https://falcosecurity.github.io/charts
