psp:
  enabled: "false"
  privileged: overlay_me

falco:
  scc:
    create: false
  falco:
    grpc:
      enabled: true
      bind_address: "unix:///run/falco/falco.sock"
      threadiness: 8

    grpc_output:
      enabled: true