psp:
  enabled: "false"
  privileged: overlay_me

falco:
  scc:
    create: false

falco-exporter:
  podSecurityPolicy:
    create: false

  serviceAccount:
    name: falco-exporter

  podSecurityContext:
    fsGroup: 2000

  serviceMonitor:
    enabled: true

  grafanaDashboard:
    enabled: true
    namespace: falco
    folder: /falco
    prometheusDatasourceName: victoria-metrics