nfs-subdir-external-provisioner:  
  nfs:
    reclaimPolicy: Retain
  
  storageClass:
    create: true
    provisionerName: k8s-sigs.io/nfs-backup-share
    defaultClass: false
    name: nfs-backup-share
    allowVolumeExpansion: true
    reclaimPolicy: Retain
    archiveOnDelete: true
    pathPattern: "${.PVC.namespace}-${.PVC.name}"
    accessModes: ReadWriteOnce

  leaderElection:
    enabled: true

  rbac:
    create: true
  
  podSecurityPolicy:
    enabled: true
  
  serviceAccount:
    create: true
    name: sa-nfs-backup-share

  resources: 
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 128Mi
