tenant:
  tenant:
    metrics:
      enabled: true
      port: 9000
      protocol: http
    prometheusOperator: false
    logging:
      anonymous: true
      json: true
      quiet: true
    
  ingress:
    api:
      ingressClassName: "nginx"
    console:
      ingressClassName: "nginx"
