name: helm-dependencies

on:
  # enable manual trigger
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - development
    paths:
      - '.github/workflows/helm-dependencies.yml'
      - 'dependencies.yaml'

jobs:
  helm-dependencies:
    name: Helm Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm Dependencies
        uses: hckops/actions/helm-dependencies-action@v0.10.2
        with:
          config-path: dependencies.yaml
          user-email: "meep-the-helm-bot@users.noreply.github.com"
          user-name: "Meep"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_DEFAULT_BRANCH: development
          GIT_USER_EMAIL: meep-the-helm-bot@users.noreply.github.com
          GIT_USER_NAME: Meep